// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT9WSFkCn-PS_D5lUGSJOX0sc4OPp1vW4',
    appId: '1:390073101728:web:f7ed4b662fb3308b7488c5',
    messagingSenderId: '390073101728',
    projectId: 'fpga-fota-system',
    authDomain: 'fpga-fota-system.firebaseapp.com',
    storageBucket: 'fpga-fota-system.firebasestorage.app',
    measurementId: 'G-H7F99L04HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZPxJlFoTkaslWbz-GHXyyaWnS6-TVW-8',
    appId: '1:390073101728:android:28735e1856262eb97488c5',
    messagingSenderId: '390073101728',
    projectId: 'fpga-fota-system',
    storageBucket: 'fpga-fota-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeeKiCZck3zVURgYARJu53Aaw_37eXrtc',
    appId: '1:390073101728:ios:ba5c6c9e4a85ad007488c5',
    messagingSenderId: '390073101728',
    projectId: 'fpga-fota-system',
    storageBucket: 'fpga-fota-system.firebasestorage.app',
    iosBundleId: 'com.fota.uploader',
  );
}
